# Generated by Django 2.2.6 on 2019-11-22 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='logo',
            field=models.ImageField(blank=True, default='default', upload_to='Others'),
        ),
    ]
