# Generated by Django 2.2.6 on 2019-12-01 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_events_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallary',
            name='description',
        ),
        migrations.AlterField(
            model_name='gallary',
            name='title',
            field=models.CharField(max_length=70),
        ),
    ]
