# Generated by Django 2.2.6 on 2019-12-14 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_remove_customer_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='coupon_id',
        ),
    ]
